### ISSUE TITLE
How to control when the script is loaded? (Combine cookiebot with gtag)

### ISSUE THREAD

**Issue by StijnCoolen** [ambitiondev/cookiebot#17]
I'm trying to get cookiebot to work with Google Analytics (through https://nuxt.com/modules/gtag) and the consent mode (https://support.cookiebot.com/hc/en-us/articles/360016047000-Implementing-Google-consent-mode#h_01HBWS079DZRM28JBSFD5W3S12). I can see that Cookiebot actually updates the dataLayer when consent changes, but the gtag scripts are not included in list of scripts that cookiebot has found.

GTM by default supports 7 different consent types that are automatically mapped by Cookiebot to the 4 categories used in Cookiebot CMP. I dont see anything Gtag related listed under the categories.

For cookiebot to pick up all the used scripts it needs to be loaded _before_ the scripts it needs to pick up. Is there any way to control this?

**Comment by bnachtweh** [comment]
Thank you for your issue @StijnCoolen. I've created a test release in which I've increased the priority of the Cookiebot scripts to be loaded. Can you please install the `next` tag (`3.2.1-alpha.0`): `npm install @ambitiondev/nuxt-cookiebot@next` or `yarn install @ambitiondev/nuxt-cookiebot@next`

If the test release provides the expected result, I will promote it to a new `latest` release

**Comment by StijnCoolen** [comment]
@bnachtweh thanks for looking into this! Ufortunately I still do not see the gtag cookies listed in Cookiebot. Perhaps this is a https://nuxt.com/modules/gtag issue.

**Comment by bnachtweh** [comment]
@StijnCoolen can't say for certain. Can you provide a CodeSandbox or other reproduction project so I can do some further investigation?

**Comment by bnachtweh** [comment]
@StijnCoolen I'm closing the issue for now and updated the script priority to begin with. It seems like a good practice to do so anyway. Please let me know if I need to do some further digging regarding gtag relation.
