### ISSUE TITLE
How do you trigger the consent popup?

### ISSUE THREAD

**Issue by sunscreem** [ambitiondev/cookiebot#8]
Thanks for making this @ambitiondev. 

My client want a separate button added to the site's footer to allow for changing the consent options they have already selected.

Is this possible in the Vue version?

**Comment by bnachtweh** [comment]
Hi @sunscreem, at the moment this is not possible. I will add this method in the next release. Stay tuned!

**Comment by bnachtweh** [comment]
@sunscreem in the latest version (3.1.0) you can use the `renew` method (for both Vue and Nuxt plugin) like so:

```
<script setup lang="ts">
const { renew } = useCookiebot();
</script>

<template>
  <div>
    <button @click="renew">renew</button>
  </div>
</template>
```

If you're using Vue, you'll need an import statement for the composable

**Comment by sunscreem** [comment]
@bnachtweh Massive thanks Sir! Already in and working a treat. 

Thanks again.
